# Generated by Django 2.0 on 2019-04-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yinyue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singname', models.CharField(max_length=150)),
                ('singer', models.CharField(max_length=150)),
                ('zhuanji', models.CharField(max_length=150)),
            ],
        ),
    ]
