# Generated by Django 2.0 on 2019-04-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shouji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
